version: "3.8"

services:
  auth-service-rest-api:
    container_name: auth-service-rest-api-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9999:8080"
    restart: on-failure
